main:
  - identifier: home
    name: Home
    pageRef: /
    weight: 10
    params: { enabled: true }

  - identifier: members
    name: Members
    parent: home
    pageRef: /people
    weight: 10
    params: { enabled: true }
  - identifier: vacancies
    name: Vacancies
    parent: home
    pageRef: /opportunities
    weight: 20
    params: { enabled: true }

  - identifier: research
    name: Research
    pageRef: /research
    weight: 20
    params: { enabled: true }
  - identifier: publications
    name: Publications
    parent: research
    pageRef: /publications
    weight: 10
    params: { enabled: true }
  - identifier: landscape-analysis
    name: Landscape Analysis
    parent: research
    pageRef: /landscape-analysis
    weight: 20
    params: { enabled: true }
  - identifier: projects
    name: Projects
    parent: research
    pageRef: /projects
    weight: 30
    params: { enabled: true }
  - identifier: grants
    name: Grants
    parent: research
    pageRef: /grants
    weight: 40
    params: { enabled: true }
  - identifier: emoc
    name: EMOC
    parent: research
    pageRef: /emoc
    weight: 50
    params: { enabled: true }

  - identifier: events
    name: Events
    pageRef: /events
    weight: 30
    params: { enabled: true }
  - identifier: study-group
    name: Study Group
    parent: events
    pageRef: /events/study-group
    weight: 10
    params: { enabled: true }
  - identifier: reading-group
    name: Reading Group
    parent: events
    pageRef: /events/reading-group
    weight: 20
    params: { enabled: true }
  - identifier: x-laboratory-seminar-series
    name: X-Laboratory Seminar Series
    parent: events
    pageRef: /events/x-laboratory-seminar-series
    weight: 30
    params: { enabled: true }

  - identifier: misc
    name: Misc
    weight: 40
    params: { enabled: true }
  - identifier: deadlines
    name: Deadlines
    parent: misc
    pageRef: /deadlines
    weight: 10
    params: { enabled: true }
  - identifier: materials
    name: Materials
    parent: misc
    pageRef: /materials
    weight: 20
    params: { enabled: true }
